# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-29 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='متن')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
