# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-31 00:08
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='متن'),
        ),
    ]
