# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-22 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180711_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='description',
            new_name='text',
        ),
    ]
