# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-29 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='', verbose_name='متن')),
                ('url', models.URLField(verbose_name='لینک')),
                ('image', models.ImageField(upload_to='', verbose_name='تصویر')),
            ],
        ),
    ]
