# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-29 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='تبلیغات بر اساس این شماره مربت می شوند (کوچک ترین به بزرگترین)', verbose_name='شماره'),
        ),
    ]
