# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-29 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_auto_20180729_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='images/advertisements', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='تبلیغات بر اساس این شماره مرتب می شوند (کوچک ترین به بزرگترین)', verbose_name='شماره'),
        ),
    ]
