# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-31 00:08
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_auto_20180729_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='text',
            field=tinymce.models.HTMLField(blank=True, default='', verbose_name='متن'),
        ),
    ]
