# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-29 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=50, verbose_name='عنوان')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='images/slider', verbose_name='تصویر')),
                ('url', models.URLField(verbose_name='لینک')),
                ('order', models.PositiveIntegerField(default=0, help_text='اسلایدها بر اساس این شماره مرتب می شوند (کوچک ترین به بزرگترین)', verbose_name='شماره')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
