# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-29 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_auto_20180729_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='active',
            field=models.BooleanField(default=True, help_text='اسلاید فعال در ابتدا نمایش داده می شود', verbose_name='فعال'),
            preserve_default=False,
        ),
    ]
