# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-29 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_slide_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='active',
            field=models.BooleanField(default=False, help_text='اسلاید فعال در ابتدا نمایش داده می شود', verbose_name='فعال'),
        ),
    ]
