# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-31 00:08
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_auto_20180729_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='description',
            field=tinymce.models.HTMLField(blank=True, default='', max_length=100, verbose_name='توضیحات'),
        ),
    ]
