# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-22 12:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('running_time', models.DateTimeField(verbose_name='زمان کنسرت')),
                ('length', models.PositiveIntegerField(verbose_name='مدت اجرا کنسرت')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='ConcertTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('price', models.FloatField(verbose_name='مبلغ')),
                ('row', models.PositiveIntegerField(choices=[(1, 'اول'), (2, 'دوم'), (3, 'سوم')], verbose_name='ردیف')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Concert', verbose_name='کنسرت')),
            ],
            options={
                'verbose_name_plural': 'Concert Tickets',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('release_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('running_time', models.DateTimeField(verbose_name='زمان اکران فیلم')),
                ('length', models.PositiveIntegerField(verbose_name='مدت زمان')),
                ('description', models.TextField(verbose_name='خلاصه داستان')),
                ('cover', models.ImageField(default='', upload_to='images/films/', verbose_name='کاور')),
                ('actors', models.ManyToManyField(to='tickets.Actor', verbose_name='ستارگان')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Country', verbose_name='محصول')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Director', verbose_name='کارگردان')),
            ],
        ),
        migrations.CreateModel(
            name='FilmTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('row', models.PositiveIntegerField(choices=[(1, 'اول'), (2, 'دوم'), (3, 'سوم')], verbose_name='ردیف')),
                ('price', models.FloatField(verbose_name='مبلغ')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Film', verbose_name='فیلم')),
            ],
            options={
                'verbose_name_plural': 'Film Tickets',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='ژانر')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='زبان')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('birth_day', models.DateTimeField(blank=True, default='', verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=255, verbose_name='جنسیت')),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='مکان')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.People', verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('length', models.PositiveIntegerField(verbose_name='مدت زمان')),
                ('cover', models.ImageField(default='', upload_to='images/songs/', verbose_name='کاور')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.People', verbose_name='خواننده')),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('running_time', models.DateTimeField(verbose_name='زمان نمایش فیلم')),
                ('description', models.TextField(verbose_name='خلاصه داستان')),
                ('cover', models.ImageField(default='', upload_to='images/theaters/', verbose_name='کاور')),
                ('actors', models.ManyToManyField(to='tickets.Actor', verbose_name='ستارگان')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Director', verbose_name='کارگردان')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Genre', verbose_name='ژانر')),
            ],
        ),
        migrations.CreateModel(
            name='TheaterTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('price', models.FloatField(verbose_name='مبلغ')),
                ('row', models.PositiveIntegerField(choices=[(1, 'اول'), (2, 'دوم'), (3, 'سوم')], verbose_name='ردیف')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Place', verbose_name='مکان')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Theater', verbose_name='تئاتر')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
            options={
                'verbose_name_plural': 'Theater Tickets',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.People', verbose_name='کاربر')),
            ],
        ),
        migrations.AddField(
            model_name='theater',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Writer', verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='filmticket',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Place', verbose_name='مکان'),
        ),
        migrations.AddField(
            model_name='filmticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Genre', verbose_name='ژانر'),
        ),
        migrations.AddField(
            model_name='film',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Language', verbose_name='زبان'),
        ),
        migrations.AddField(
            model_name='film',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Producer', verbose_name='تهیه کننده'),
        ),
        migrations.AddField(
            model_name='film',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Writer', verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='director',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.People', verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='concertticket',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Place', verbose_name='مکان'),
        ),
        migrations.AddField(
            model_name='concertticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
        migrations.AddField(
            model_name='concert',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.People', verbose_name='خواننده'),
        ),
        migrations.AddField(
            model_name='concert',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Place', verbose_name='مکان'),
        ),
        migrations.AddField(
            model_name='concert',
            name='songs',
            field=models.ManyToManyField(to='tickets.Song', verbose_name='ترانه ها'),
        ),
        migrations.AddField(
            model_name='actor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.People', verbose_name='کاربر'),
        ),
    ]
