# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-10 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='زمان کنسرت')),
                ('description', models.TextField(verbose_name='خلاصه داستان')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='نام')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('release_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان انتشار')),
                ('runnig_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان اجرا فیلم')),
                ('length', models.PositiveIntegerField(verbose_name='مدت زمان')),
                ('description', models.TextField(verbose_name='خلاصه داستان')),
                ('actors', models.ManyToManyField(to='tickets.Actor', verbose_name='ستارگان')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Country', verbose_name='محصول')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Director', verbose_name='کارگردان')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='ژانر')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='زبان')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('birth_day', models.DateTimeField(blank=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], max_length=255, verbose_name='جنسیت')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('length', models.PositiveIntegerField(verbose_name='مدت زمان')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.People', verbose_name='خواننده')),
            ],
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('runnig_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان نمایش فیلم')),
                ('description', models.TextField(verbose_name='خلاصه داستان')),
                ('actors', models.ManyToManyField(to='tickets.Actor', verbose_name='ستارگان')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Director', verbose_name='کارگردان')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Genre', verbose_name='ژانر')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('place', models.CharField(max_length=255, verbose_name='مکان')),
                ('date', models.DateTimeField(verbose_name='زمان')),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.People', verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='ConcertTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.Ticket')),
            ],
            bases=('tickets.ticket',),
        ),
        migrations.CreateModel(
            name='FilmTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.Ticket')),
            ],
            bases=('tickets.ticket',),
        ),
        migrations.CreateModel(
            name='TheaterTicket',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tickets.Ticket')),
            ],
            bases=('tickets.ticket',),
        ),
        migrations.AddField(
            model_name='theater',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Writer', verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Genre', verbose_name='ژانر'),
        ),
        migrations.AddField(
            model_name='film',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Language', verbose_name='زبان'),
        ),
        migrations.AddField(
            model_name='film',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Writer', verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='director',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.People', verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='concert',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Song', verbose_name='خواننده'),
        ),
        migrations.AddField(
            model_name='actor',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.People', verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='theaterticket',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Theater', verbose_name='تئاتر'),
        ),
        migrations.AddField(
            model_name='filmticket',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Film', verbose_name='فیلم'),
        ),
        migrations.AddField(
            model_name='concertticket',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Concert', verbose_name='کنسرت'),
        ),
    ]
