# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-31 00:08
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='خلاصه داستان'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='خلاصه داستان'),
        ),
    ]
