# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-07-15 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='cover',
            field=models.ImageField(default='', upload_to='images/films/', verbose_name='کاور'),
        ),
        migrations.AddField(
            model_name='song',
            name='cover',
            field=models.ImageField(default='', upload_to='images/songs/', verbose_name='کاور'),
        ),
        migrations.AddField(
            model_name='theater',
            name='cover',
            field=models.ImageField(default='', upload_to='images/theaters/', verbose_name='کاور'),
        ),
    ]
